// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusPaid      OrderStatus = "paid"
	OrderStatusCancelled OrderStatus = "cancelled"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusShipped   OrderStatus = "shipped"
	OrderStatusRefunded  OrderStatus = "refunded"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Order struct {
	ID             int64
	UserID         int64
	Status         OrderStatus
	SubtotalAmount decimal.Decimal
	TaxAmount      decimal.Decimal
	ShippingAmount decimal.Decimal
	DiscountAmount decimal.Decimal
	TotalAmount    decimal.Decimal
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OrderItem struct {
	ID          int64
	OrderID     int64
	ProductID   int64
	VariantID   int64
	ProductName string
	VariantName string
	Sku         string
	UnitPrice   decimal.Decimal
	Quantity    int64
	TotalPrice  decimal.Decimal
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
