// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstore

import (
	"context"

	"github.com/shopspring/decimal"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, variant_id, product_name, variant_name, sku, unit_price, quantity, total_price)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
    id, order_id, product_id, variant_id, product_name, variant_name, sku, unit_price, quantity, total_price, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID     int64
	ProductID   int64
	VariantID   int64
	ProductName string
	VariantName string
	Sku         string
	UnitPrice   decimal.Decimal
	Quantity    int64
	TotalPrice  decimal.Decimal
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.VariantID,
		arg.ProductName,
		arg.VariantName,
		arg.Sku,
		arg.UnitPrice,
		arg.Quantity,
		arg.TotalPrice,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.UnitPrice,
		&i.Quantity,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE id = $1
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItem, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT
    id,
    user_id,
    status,
    subtotal_amount,
    tax_amount,
    shipping_amount,
    discount_amount,
    total_amount,
    created_at,
    updated_at
FROM
    orders
WHERE
    id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalAmount,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT
    id,
    order_id,
    product_id,
    variant_id,
    product_name,
    variant_name,
    sku,
    unit_price,
    quantity,
    total_price,
    created_at,
    updated_at
FROM
    order_items
WHERE
    id = $1
`

func (q *Queries) GetOrderItem(ctx context.Context, id int64) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.UnitPrice,
		&i.Quantity,
		&i.TotalPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
INSERT INTO orders (user_id, status, subtotal_amount, tax_amount, shipping_amount, discount_amount, total_amount)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, user_id, status, subtotal_amount, tax_amount, shipping_amount, discount_amount, total_amount, created_at, updated_at
`

type InsertOrderParams struct {
	UserID         int64
	Status         OrderStatus
	SubtotalAmount decimal.Decimal
	TaxAmount      decimal.Decimal
	ShippingAmount decimal.Decimal
	DiscountAmount decimal.Decimal
	TotalAmount    decimal.Decimal
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.UserID,
		arg.Status,
		arg.SubtotalAmount,
		arg.TaxAmount,
		arg.ShippingAmount,
		arg.DiscountAmount,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalAmount,
		&i.TaxAmount,
		&i.ShippingAmount,
		&i.DiscountAmount,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
