// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlstore

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	ID        int64
	UserID    pgtype.Int8
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CartItem struct {
	ID        int64
	CartID    int64
	ProductID pgtype.Int8
	VariantID pgtype.Int8
	Quantity  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
