// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCart = `-- name: DeleteCart :exec
DELETE FROM carts
WHERE id = $1
`

func (q *Queries) DeleteCart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1
`

func (q *Queries) DeleteCartItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCartItem, id)
	return err
}

const getCart = `-- name: GetCart :one
SELECT
    id,
    user_id,
    created_at,
    updated_at
FROM
    carts
WHERE
    id = $1
`

func (q *Queries) GetCart(ctx context.Context, id int64) (Cart, error) {
	row := q.db.QueryRow(ctx, getCart, id)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItem = `-- name: GetCartItem :one
SELECT
    id,
    cart_id,
    product_id,
    variant_id,
    quantity,
    created_at,
    updated_at
FROM
    cart_items
WHERE
    id = $1
`

func (q *Queries) GetCartItem(ctx context.Context, id int64) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItem, id)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCart = `-- name: InsertCart :one
INSERT INTO carts (user_id)
    VALUES ($1)
RETURNING
    id, user_id, created_at, updated_at
`

func (q *Queries) InsertCart(ctx context.Context, userID pgtype.Int8) (Cart, error) {
	row := q.db.QueryRow(ctx, insertCart, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :one
INSERT INTO cart_items (cart_id, product_id, variant_id, quantity)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, variant_id)
    DO UPDATE SET
        quantity = cart_items.quantity + EXCLUDED.quantity,
        updated_at = now()
    RETURNING
        id,
        cart_id,
        product_id,
        variant_id,
        quantity,
        created_at,
        updated_at
`

type InsertCartItemParams struct {
	CartID    int64
	ProductID pgtype.Int8
	VariantID pgtype.Int8
	Quantity  int32
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, insertCartItem,
		arg.CartID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCartItem = `-- name: UpdateCartItem :one
INSERT INTO cart_items (cart_id, product_id, variant_id, quantity)
    VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, variant_id)
    DO UPDATE SET
        quantity = quantity + EXCLUDED.quantity,
        updated_at = now()
    RETURNING
        id,
        cart_id,
        product_id,
        variant_id,
        quantity,
        created_at,
        updated_at
`

type UpdateCartItemParams struct {
	CartID    int64
	ProductID pgtype.Int8
	VariantID pgtype.Int8
	Quantity  int32
}

func (q *Queries) UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItem,
		arg.CartID,
		arg.ProductID,
		arg.VariantID,
		arg.Quantity,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ProductID,
		&i.VariantID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
