ALTER TABLE products
    ALTER COLUMN sku TYPE VARCHAR(64),
    ALTER COLUMN slug TYPE VARCHAR(128),
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN meta_title TYPE VARCHAR(255);

ALTER TABLE products_variants
    ALTER COLUMN slug TYPE VARCHAR(64),
    ALTER COLUMN name TYPE VARCHAR(255);

ALTER TABLE categories
    ALTER COLUMN name TYPE VARCHAR(255),
    ALTER COLUMN slug TYPE VARCHAR(128);
