// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/product/v1/product.proto

package productpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckVariantExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     int64                  `protobuf:"varint,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVariantExistsRequest) Reset() {
	*x = CheckVariantExistsRequest{}
	mi := &file_proto_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVariantExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVariantExistsRequest) ProtoMessage() {}

func (x *CheckVariantExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVariantExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckVariantExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *CheckVariantExistsRequest) GetVariantId() int64 {
	if x != nil {
		return x.VariantId
	}
	return 0
}

type CheckVariantExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckVariantExistsResponse) Reset() {
	*x = CheckVariantExistsResponse{}
	mi := &file_proto_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckVariantExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckVariantExistsResponse) ProtoMessage() {}

func (x *CheckVariantExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckVariantExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckVariantExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *CheckVariantExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_proto_product_v1_product_proto protoreflect.FileDescriptor

const file_proto_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/product/v1/product.proto\x12\n" +
	"product.v1\":\n" +
	"\x19CheckVariantExistsRequest\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\x03R\tvariantId\"4\n" +
	"\x1aCheckVariantExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2u\n" +
	"\x0eProductService\x12c\n" +
	"\x12CheckVariantExists\x12%.product.v1.CheckVariantExistsRequest\x1a&.product.v1.CheckVariantExistsResponseBAZ?github.com/amane15/ecom_microservice/proto/product/v1;productpbb\x06proto3"

var (
	file_proto_product_v1_product_proto_rawDescOnce sync.Once
	file_proto_product_v1_product_proto_rawDescData []byte
)

func file_proto_product_v1_product_proto_rawDescGZIP() []byte {
	file_proto_product_v1_product_proto_rawDescOnce.Do(func() {
		file_proto_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_proto_rawDesc), len(file_proto_product_v1_product_proto_rawDesc)))
	})
	return file_proto_product_v1_product_proto_rawDescData
}

var file_proto_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_product_v1_product_proto_goTypes = []any{
	(*CheckVariantExistsRequest)(nil),  // 0: product.v1.CheckVariantExistsRequest
	(*CheckVariantExistsResponse)(nil), // 1: product.v1.CheckVariantExistsResponse
}
var file_proto_product_v1_product_proto_depIdxs = []int32{
	0, // 0: product.v1.ProductService.CheckVariantExists:input_type -> product.v1.CheckVariantExistsRequest
	1, // 1: product.v1.ProductService.CheckVariantExists:output_type -> product.v1.CheckVariantExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_product_v1_product_proto_init() }
func file_proto_product_v1_product_proto_init() {
	if File_proto_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_v1_product_proto_rawDesc), len(file_proto_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_v1_product_proto_goTypes,
		DependencyIndexes: file_proto_product_v1_product_proto_depIdxs,
		MessageInfos:      file_proto_product_v1_product_proto_msgTypes,
	}.Build()
	File_proto_product_v1_product_proto = out.File
	file_proto_product_v1_product_proto_goTypes = nil
	file_proto_product_v1_product_proto_depIdxs = nil
}
