// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlstore

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories
WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM products_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVariant, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    categories
WHERE
    id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id,
    name,
    slug,
    description,
    short_description,
    meta_title,
    meta_description,
    status,
    default_variant_id,
    created_at,
    updated_at,
    deleted_at
FROM
    products
WHERE
    id = $1
`

type GetProductRow struct {
	ID               int64
	Name             string
	Slug             string
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           ProductStatus
	DefaultVariantID sql.NullInt64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

func (q *Queries) GetProduct(ctx context.Context, id int64) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Status,
		&i.DefaultVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVariant = `-- name: GetVariant :one
SELECT
    id,
    product_id,
    slug,
    name,
    price,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    products_variants
WHERE
    id = $1
`

func (q *Queries) GetVariant(ctx context.Context, id int64) (ProductsVariant, error) {
	row := q.db.QueryRowContext(ctx, getVariant, id)
	var i ProductsVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVariantByProduct = `-- name: GetVariantByProduct :one
SELECT
    count(*)
FROM
    products_variants
WHERE
    product_id = $1
`

func (q *Queries) GetVariantByProduct(ctx context.Context, productID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVariantByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, slug, description, is_active)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, name, slug, description, is_active, created_at, updated_at
`

type InsertCategoryParams struct {
	Name        string
	Slug        string
	Description sql.NullString
	IsActive    bool
}

type InsertCategoryRow struct {
	ID          int64
	Name        string
	Slug        string
	Description sql.NullString
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (InsertCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, insertCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsActive,
	)
	var i InsertCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (name, slug, description, short_description, meta_title, meta_description, status)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
    id, name, slug, description, short_description, meta_title, meta_description, status, default_variant_id, created_at, updated_at
`

type InsertProductParams struct {
	Name             string
	Slug             string
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           ProductStatus
}

type InsertProductRow struct {
	ID               int64
	Name             string
	Slug             string
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           ProductStatus
	DefaultVariantID sql.NullInt64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Status,
	)
	var i InsertProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Status,
		&i.DefaultVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVariant = `-- name: InsertVariant :one
INSERT INTO products_variants (product_id, slug, name, price, is_active)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, product_id, slug, name, price, is_active, created_at, updated_at, deleted_at
`

type InsertVariantParams struct {
	ProductID int64
	Slug      string
	Name      string
	Price     decimal.Decimal
	IsActive  bool
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) (ProductsVariant, error) {
	row := q.db.QueryRowContext(ctx, insertVariant,
		arg.ProductID,
		arg.Slug,
		arg.Name,
		arg.Price,
		arg.IsActive,
	)
	var i ProductsVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    categories
WHERE
    is_active = TRUE
ORDER BY
    id
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT
    id,
    product_id,
    slug,
    name,
    price,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    products_variants
WHERE
    product_id = $1
`

func (q *Queries) ListProductVariants(ctx context.Context, productID int64) ([]ProductsVariant, error) {
	rows, err := q.db.QueryContext(ctx, listProductVariants, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsVariant
	for rows.Next() {
		var i ProductsVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Slug,
			&i.Name,
			&i.Price,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    name,
    slug,
    description,
    short_description,
    meta_title,
    meta_description,
    status,
    default_variant_id,
    created_at,
    updated_at,
    deleted_at
FROM
    products
WHERE
    status = 'active'
ORDER BY
    id
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	ID               int64
	Name             string
	Slug             string
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           ProductStatus
	DefaultVariantID sql.NullInt64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	DeletedAt        sql.NullTime
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Status,
			&i.DefaultVariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE
    categories
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    is_active = COALESCE($4, is_active)
WHERE
    id = $1
RETURNING
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type UpdateCategoryParams struct {
	ID          int64
	Name        sql.NullString
	Description sql.NullString
	IsActive    sql.NullBool
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE
    products
SET
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    short_description = COALESCE($4, short_description),
    meta_title = COALESCE($5, meta_title),
    meta_description = COALESCE($6, meta_description),
    status = COALESCE($7, status),
    default_variant_id = COALESCE($8, default_variant_id),
    updated_at = now()
WHERE
    id = $1
RETURNING
    id,
    name,
    slug,
    description,
    short_description,
    meta_title,
    meta_description,
    status,
    default_variant_id,
    created_at,
    updated_at
`

type UpdateProductParams struct {
	ID               int64
	Name             sql.NullString
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           NullProductStatus
	DefaultVariantID sql.NullInt64
}

type UpdateProductRow struct {
	ID               int64
	Name             string
	Slug             string
	Description      sql.NullString
	ShortDescription sql.NullString
	MetaTitle        sql.NullString
	MetaDescription  sql.NullString
	Status           ProductStatus
	DefaultVariantID sql.NullInt64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ShortDescription,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Status,
		arg.DefaultVariantID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Status,
		&i.DefaultVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE
    products_variants
SET
    name = COALESCE($2, name),
    price = COALESCE($3, price),
    is_active = COALESCE($4, is_active)
WHERE
    id = $1
RETURNING
    id,
    product_id,
    slug,
    name,
    price,
    is_active,
    created_at,
    updated_at,
    deleted_at
`

type UpdateVariantParams struct {
	ID       int64
	Name     sql.NullString
	Price    sql.NullString
	IsActive sql.NullBool
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (ProductsVariant, error) {
	row := q.db.QueryRowContext(ctx, updateVariant,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.IsActive,
	)
	var i ProductsVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
