// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteVariant(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetProduct(ctx context.Context, id int64) (GetProductRow, error)
	GetVariant(ctx context.Context, id int64) (ProductsVariant, error)
	GetVariantByProduct(ctx context.Context, productID sql.NullInt64) (int64, error)
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (InsertCategoryRow, error)
	InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error)
	InsertVariant(ctx context.Context, arg InsertVariantParams) (InsertVariantRow, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
}

var _ Querier = (*Queries)(nil)
