// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package data

import (
	"context"
	"database/sql"
	"time"
)

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM products_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVariant, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    categories
WHERE
    id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
    id,
    name,
    slug,
    description,
    short_description,
    meta_title,
    meta_description,
    status,
    default_variant_id,
    created_at,
    updated_at,
    deleted_at
FROM
    products
WHERE
    id = $1
`

type GetProductRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	ShortDescription sql.NullString `json:"short_description"`
	MetaTitle        sql.NullString `json:"meta_title"`
	MetaDescription  sql.NullString `json:"meta_description"`
	Status           ProductStatus  `json:"status"`
	DefaultVariantID sql.NullInt64  `json:"default_variant_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) GetProduct(ctx context.Context, id int64) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDescription,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.Status,
		&i.DefaultVariantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVariant = `-- name: GetVariant :one
SELECT
    id,
    product_id,
    slug,
    name,
    price,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    products_variants
WHERE
    id = $1
`

func (q *Queries) GetVariant(ctx context.Context, id int64) (ProductsVariant, error) {
	row := q.db.QueryRowContext(ctx, getVariant, id)
	var i ProductsVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Slug,
		&i.Name,
		&i.Price,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getVariantByProduct = `-- name: GetVariantByProduct :one
SELECT
    count(*)
FROM
    products_variants
WHERE
    product_id = $1
`

func (q *Queries) GetVariantByProduct(ctx context.Context, productID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVariantByProduct, productID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (name, slug, description, is_active)
    VALUES ($1, $2, $3, $4)
RETURNING
    id, created_at, updated_at
`

type InsertCategoryParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	IsActive    bool           `json:"is_active"`
}

type InsertCategoryRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (InsertCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, insertCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.IsActive,
	)
	var i InsertCategoryRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertProduct = `-- name: InsertProduct :one
INSERT INTO products (name, slug, description, short_description, meta_title, meta_description, status, default_variant_id)
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    id, created_at, updated_at
`

type InsertProductParams struct {
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	ShortDescription sql.NullString `json:"short_description"`
	MetaTitle        sql.NullString `json:"meta_title"`
	MetaDescription  sql.NullString `json:"meta_description"`
	Status           ProductStatus  `json:"status"`
	DefaultVariantID sql.NullInt64  `json:"default_variant_id"`
}

type InsertProductRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) (InsertProductRow, error) {
	row := q.db.QueryRowContext(ctx, insertProduct,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDescription,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.Status,
		arg.DefaultVariantID,
	)
	var i InsertProductRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertVariant = `-- name: InsertVariant :one
INSERT INTO products_variants (product_id, slug, name, price, is_active)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, created_at, updated_at
`

type InsertVariantParams struct {
	ProductID sql.NullInt64  `json:"product_id"`
	Slug      string         `json:"slug"`
	Name      sql.NullString `json:"name"`
	Price     sql.NullString `json:"price"`
	IsActive  bool           `json:"is_active"`
}

type InsertVariantRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) (InsertVariantRow, error) {
	row := q.db.QueryRowContext(ctx, insertVariant,
		arg.ProductID,
		arg.Slug,
		arg.Name,
		arg.Price,
		arg.IsActive,
	)
	var i InsertVariantRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    name,
    slug,
    description,
    is_active,
    created_at,
    updated_at,
    deleted_at
FROM
    categories
WHERE
    is_active = TRUE
ORDER BY
    id
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
    id,
    name,
    slug,
    description,
    short_description,
    meta_title,
    meta_description,
    status,
    default_variant_id,
    created_at,
    updated_at,
    deleted_at
FROM
    products
WHERE
    status = 'active'
ORDER BY
    id
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductsRow struct {
	ID               int64          `json:"id"`
	Name             string         `json:"name"`
	Slug             string         `json:"slug"`
	Description      sql.NullString `json:"description"`
	ShortDescription sql.NullString `json:"short_description"`
	MetaTitle        sql.NullString `json:"meta_title"`
	MetaDescription  sql.NullString `json:"meta_description"`
	Status           ProductStatus  `json:"status"`
	DefaultVariantID sql.NullInt64  `json:"default_variant_id"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDescription,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.Status,
			&i.DefaultVariantID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
