// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"database/sql"
	"time"
)

type Cart struct {
	ID        int64         `json:"id"`
	UserID    sql.NullInt64 `json:"user_id"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type CartItem struct {
	ID        int64         `json:"id"`
	CartID    int64         `json:"cart_id"`
	ProductID sql.NullInt64 `json:"product_id"`
	VariantID sql.NullInt64 `json:"variant_id"`
	Quantity  int32         `json:"quantity"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
