// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package data

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteCart(ctx context.Context, id int64) error
	DeleteCartItem(ctx context.Context, id int64) error
	GetCart(ctx context.Context, id int64) (Cart, error)
	GetCartItem(ctx context.Context, id int64) (CartItem, error)
	InsertCart(ctx context.Context, userID sql.NullInt64) (Cart, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) (InsertCartItemRow, error)
	UpdateCartItem(ctx context.Context, arg UpdateCartItemParams) (CartItem, error)
}

var _ Querier = (*Queries)(nil)
